apiVersion: apps/v1
kind: Deployment
metadate:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: zloymumu/k8-service-test:0.0.2
          ports:
            - containerPort: 8080